spring:
  application:
    name: zuul-server

server:
  port: 8090
  compression:
    enabled: true

zuul:
  routes:
    concert:
      path: /ticketplus/**
      service-id: concert-service
      stripPrefix: true
    ticket:
      path: /ticketplus/**
      service-id: ticket-service
      stripPrefix: true
    order:
      path: /ticketplus/**
      service-id: order-service
      strip-prefix: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
